<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Arial, sans-serif; color: #111; padding: 24px; }
    .muted { color: #666; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th, td { padding: 8px; border: 1px solid #e5e7eb; }
    th { background: #f3f4f6; text-align: left; }
    .right { text-align: right; }
    .total { font-size: 16px; }
  </style>
</head>
<body>
  <h1 style="margin-bottom: 2px;">{{ $business['company_name'] ?? 'FinOS' }}</h1>
  <p class="muted" style="margin-top: 0;">{{ $business['tax_id'] ?? '' }} {{ $business['address'] ?? '' }}</p>

  <div style="display: flex; justify-content: space-between; margin: 24px 0;">
    <div>
      <div class="muted">Bill to</div>
      <div><strong>{{ $invoice->customer->name ?? 'Customer' }}</strong></div>
      <div class="muted">{{ $invoice->customer->email ?? '' }}</div>
    </div>
    <div style="text-align: right;">
      <div class="muted">Invoice</div>
      <div><strong>{{ $invoice->number }}</strong></div>
      <div class="muted">Issued {{ $invoice->issue_date }} &middot; Due {{ $invoice->due_date ?? '—' }}</div>
    </div>
  </div>

  <table>
    <tr>
      <th>Description</th>
      <th class="right">Qty</th>
      <th class="right">Unit price</th>
      <th class="right">Tax %</th>
      <th class="right">Amount</th>
    </tr>
    @foreach ($invoice->items as $item)
      <tr>
        <td>{{ $item->description }}</td>
        <td class="right">{{ $item->quantity }}</td>
        <td class="right">{{ number_format($item->unit_price, 2) }}</td>
        <td class="right">{{ $item->tax_rate }}</td>
        <td class="right">{{ number_format($item->amount, 2) }}</td>
      </tr>
    @endforeach
  </table>

  <table style="width: auto; margin-left: auto; margin-top: 12px;">
    <tr><td class="right muted">Subtotal</td><td class="right">{{ number_format($invoice->subtotal, 2) }}</td></tr>
    <tr><td class="right muted">Tax</td><td class="right">{{ number_format($invoice->tax, 2) }}</td></tr>
    <tr><td class="right total"><strong>Total</strong></td><td class="right total"><strong>{{ $invoice->currency }} {{ number_format($invoice->total, 2) }}</strong></td></tr>
  </table>

  @if ($invoice->notes)
    <p class="muted" style="margin-top: 24px;">{{ $invoice->notes }}</p>
  @endif
  <p class="muted" style="margin-top: 24px;">Generated by FinOS.</p>
</body>
</html>
